---
title: "Arbeitsblatt 09 - Mehrebenenanalyse"
format: 
  html:
    toc: true
    toc-location: right
    toc-depth: 4
    toc-title: Inhaltsverzeichnis
enigine: knitr
filters: 
 - webr
backgroundcolor: white
monobackgroundcolor: grey
---

```{r}
#| include: false
```

### Aufgabe 40

#### a)

Bestimmen Sie für folgenden Beispiele jewils die zwei Ebenen, und geben Sie für jede Ebene die zugehörigen Variablen an:

1.  Stellen Sie sich vor, Sie arbeiten im Bereich der Entwicklungs- und Schulpsychologie und interessieren sich (u.a.) für den Zusammenhang zwischen Motivation und mathematischen Fähigkeiten. Sie verfügen über einen Datensatz, indem für 210 Schulen und dort für je 100 Schüler die Motivation und die Leistung in einem mathem.-nat. Test erhoben wurde. Damit Sie den Einfluss des Schwerpunkts der Schule berücksichtigen können, weisen jeweils 70 der Schulen einen gemeinsamen Schwerpunkt auf (mathemat-naturwissenschaftlich, sprachlich, künstlerisch). Für jeden Schüler wurde zusätzlich eine (subjektive) Leistungsbeurteilung durch einen Lehrer vorgenommen.

2.  Es sind harte Zeiten für den Weihnachtsmann, die Weltbevölkerung wächst und so auchdie Anzahl der Kinder. Es stellt sich daher die Frage ob die Spielzeugproduktion amNordpol stärker mit Maschinen durchgeführt werden sollte. Um die Kinderzufriedenheitsicherzustellen, fand im Jahr 2020 ein grossangelegter Test statt. Es wurden 600 zufällige Elfenwerkstätten ausgewählt, wobei 300 mit Maschinen ausgestattet wurden, während die 300 anderen bei Handarbeit blieben. In jeweils einem Drittel der Werkstätten wurden ungelernte Elfen eingesetzt, einem weiteren Drittel neu ausgebildete Elfen und im letzten Drittel Profielfen. Aus jeder Werkstatt wurden zufällig 200 Geschenke ausgewählt und jeweils der Aufwand in der Herstellung und die Kinderzufriedenheit je Geschenk erfasst.

3.  Es gibt die Hypothese, dass Hirsche über mehrere Generationen kleinere Geweihe ausbilden, wenn Sie bejagt werden. Denn meist werden die Tiere geschossen, welche das schönste Geweih haben. Eine Biologin möchte diese Theorie prüfen. Dazu bestimmt Sie für 40 zufällig ausgewählte Wälder in der Schweiz ob diese ein Naturschutzgebiet sind, saisonal bejagt, oder ganzjährig bejagt werden dürfen. Per Fotofalle macht sie in jedem der Wälder anschließend Aufnahmen von mindestens 25 verschiedenen Hirschen um deren Geweihgröße (in cm) zu ermitteln. Da große Geweihe bei Revierkämpfen von Vorteil sind, erfasst Sie außerdem die Anzahl an Hirschen pro qm² für jeden Wald, sowie das geschätzte Alter jedes fotografierten Tieres in Jahren.

4.  Ein befreundeter Bauer bittet Sie um Rat. Er möchte wissen, wie sich eine künstliche Bewässerung auf den Ertrag seiner Felder auswirkt. Er besitzt insgesamt 50 Felder. Auf jedem Feld hat er je 5 bis 10 Bereiche als Testflächen abgesteckt. Diese Flächen werden entweder künstlich bewässert, oder nicht. Da der Ertrag (in t) sicherlich nicht nur von der Bewässerung abhängig ist, sondern auch von anderen Faktoren, erfassen sie zusätzlich folgende Faktoren: Die Bodenqualität des Feldes (auf einer metrischen Skala), die angebaute Pflanze auf jeder Testfläche (Mais, Kartoffeln, Weizen oder Gerste) und die Größe jeder Testfläche (in m²).

#### b)

Stellen Sie für jedes Beispiele (a I – IV) das zugehörige Intercept-Only-Modell auf. Wofür wird dieses Modell hauptsächlich genutzt?

#### c)

Wir wollen jetzt für die Beispiele I und II das Intercept-Only-Modell in R berechnen. Dafür benötigen wir die Pakete lme4 und lmerTest. Installieren und laden Sie diese. Danach ist das Vorgehen zunächst ähnlich zur linearen Regression, wir brauchen wieder den summary()-Befehl, aber statt lm() benutzen wir jetzt lmer(). Der Befehl ist gleich aufgebaut wie lm(), allerdings müssen wir jetzt neben den festen Effekten (wie wir es kennen), die zufälligen Effekte hinzufügen, dazu kommt bei der Formel ein Term nach folgender Struktur hinzu (1 + ...\|2.\_EBENE), wobei statt +… die zufälligen Effekte aufgeführt werden (nach dem gleichen Schema wie die festen Effekte). Statt des Platzhalters 2.\_EBENE, benennen Sie die Spalte im Datensatz, die angibt zu welchem Element der zweiten Ebene diese Zeile gehört. Ein Beispiel:<br>yij = b0j + b1j \* X1ij + eij<br>b0j = c00 + c01 \* x2j + u0j<br>b1j = c10 + u1j<br>entspricht dem Befehl: lmer(Y \~ X1 + X2 + (1 + X1 \| Gruppe), df). Wobei die Spalte Gruppe den Index j definiert. Es werden drei feste Effekte und drei zufällige Effekte geschätzt. Laden Sie die Datensätze SchuleMotivation.csv und Weihnachtsmann.csv und schätzen Sie für beide jeweils das Intercept-Only-Modell. Berechnen Sie anschließend die Intraklassenkorrelation.

```{webr-r}
#| autorun: false
#| read-only: false

```

#### d)

Für alle weiteren Analysen müssen wir die Datensätze zunächst vorbereiten. Führen Sie für alle nominalen Daten je eine Dummykodierung mit den Referenzen mathematisch-naturwissenschaftlich, Handarbeit und ungelernt. Zentrieren Sie alle intervallskalierten UVs.

```{webr-r}
#| autorun: false
#| read-only: false

```

#### e)

Stellen Sie für beide Beispiele jeweils das Modell mit festen Effekten auf und schätzen Sie anschließend deren Werte in R.

```{webr-r}
#| autorun: false
#| read-only: false

```

#### f)

Stellen Sie für beide Beispiele jeweils das Modell mit zufälligen Effekten auf und schätzen Sie anschließend deren Werte in R.

```{webr-r}
#| autorun: false
#| read-only: false

```

#### g)

Stellen Sie jetzt die vollständigen Modelle auf und schätzen Sie anschließend deren Werte in R.

```{webr-r}
#| autorun: false
#| read-only: false

```

#### h)

Wir wollen nun unsere Modelle etwas vereinfachen. Entfernen Sie zunächst die zufälligen Effekte für die Interaktion und den Haupteffekt des Lehrerurteils aus Ihrem vollständigen Modell. Entfernen Sie anschließend für beide vollständigen Modelle die nicht signifikanten festen Effekte bis Sie ein sparsames Modell erhalten. Vergleichen Sie dieses jeweils mit dem vollständigen Modell (bzw. mit dem Modell ohne die beiden zufälligen Effekte). Welches Modell ist zu bevorzugen?

```{webr-r}
#| autorun: false
#| read-only: false

```

#### i)

Wir wollen für unsere beiden gewählten Modelle die Homoskedastizität und die Normalverteilung der Residuen überprüfen (notwendige Prüfungen, aber eigentlich nicht hinreichend).

```{webr-r}
#| autorun: false
#| read-only: false

```
