---
title: "Lachen is wie Balsam auf der Seele!"
format: html
resources: Weihnachtsmann.csv
engine: knitr
filters: 
 - webr
backgroundcolor: white
monobackgroundcolor: yellow
---

## Linear Regression Model

```{r}
#| echo: false

# Imer(AV ~ 1 + (1 | ID 2. Ebene), df)

require(lmerTest)
  
# Datensatz: Weihnachtsmann

  library(readr)
  Weihnachtsmann <- read_csv("Weihnachtsmann.csv")
  dfWm <- Weihnachtsmann

  E_dfWm <- lmer(Zufriedenheit ~ 1 + (1 | Werkstatt), dfWm)
  summary(E_dfWm)

  # Intraklassenkorrelation = u0(j) / var(AV)
  11.57 / var(dfWm$Zufriedenheit) # WENN hoch -> Mehrebeneanalyse bzw. 2. Ebene beachten ???

```

## Plots

```{r}
#| echo: false

plot(
  mpg ~ wt,
  data = mtcars,
  col = "blue", 
  xlab = "Miles/(US) gallon",
  ylab = "Weight (1000 lbs)",
  main = "Miles per Gallon and Weight of Cars",
  sub = "Source: 1974 Motor Trend US magazine."
)
```

## Lösungsanzeige

```{webr-r}
#| context: setup

library(readr)
Weihnachtsmann <- read_csv(url("https://pichelmann.org/datafiles/Weihnachtsmann.csv"))
fit <- lm(Zufriedenheit ~ Ausbildung, data = Weihnachtsmann)
summary(fit)

answer_frame <- data.frame(
  problem = c("1a", "1b", "2"),
  answer = c(fit$coefficients),
  tol = c(0, 0, 1/32)
)

check <- function(problem, answer) {
  aframe <- answer_frame
  if(!problem %in% aframe$problem) {
    error_msg <- paste0("Please enter a valid problem. (", paste0(aframe$problem, collapse = ","), ")")
    stop(error_msg)
  }

  solution <- aframe[which(aframe$problem == problem), "answer"]

  ifelse(
    all.equal(answer, solution, tolerance = 0.001) == TRUE,
    "Correct! Well done.",
    "Incorrect! Good attempt. Let's try again?"
  )
}
```

```{webr-r}
#| autorun: false
#| read-only: false
#| editor-code-line-numbers: 3

student_solution_1 = 19
student_solution_2 = 10

check(problem = "1c", answer = student_solution_1)
check(problem = "1a", answer = student_solution_2)

```
